version: "2"

checks:
  similar-code:
    enabled: false
  argument-count:
      config:
        threshold: 5

plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc.json

exclude_patterns:
  - "**/node_modules/"
  - "dist/"
  - "coverage/"
  - "src/__mocks__/"
  - "src/__snapshots__/"
  - "src/*.test.js"
  - "webpack.config.js"
